# Generated by Django 6.0.5 on 2026-05-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbs/'),
        ),
    ]
